Modular Building
yuwui/Uchu pull request #297
Opened 2021-09-10 13:20 UTC by TecCheck

With this PR I'd like to implement a few functions from the modular building (rockets and cars). 

These are the things that I know worked in live but do not in Uchu (atm):
* [x] Dropping a model into the builder when in build mode  (#157) 
* [ ] Dropping a model into the builder when not in build mode (#63)
* [ ] Placing parts on the ground
* [ ] Picking parts up from the ground

2021-09-10 13:25 UTC, TecCheck commented
Right now I'm stuck at the second point, because the client doesn't show the rocket even though it's moved into the temp-models inventory. There must be some way to tell the client but I just can't figure out how...

2021-09-10 15:13 UTC, Jettford commented
Maybe you need the ModularAssemblyComponent, I think that is a replica component that you need.

2021-09-10 15:15 UTC, TecCheck commented
Do you mean ModularBuilderComponent?

2021-09-11 15:07 UTC, enteryournamehere commented
I believe Jett is referring to [this](https://lcdruniverse.org/lu_packets/lu_packets/raknet/client/replica/module_assembly/index.html) replica component (also in [lu_replica_packets docs](https://docs.google.com/document/d/1V_yhtj91QG0VBfMnmD5zC44DXwCRqjbBN98HoXXC7qs/edit#heading=h.xse7mjmay9p7#))

2021-09-11 16:46 UTC, TecCheck commented
I understand this as following: some or all components on a gameobject are serialized and sent to the client? That would mean I need to implement a struct with the same properties as the live implementation. That would then fix (some of) the problems?

2021-09-11 19:06 UTC, enteryournamehere commented
> I understand this as following: some or all components on a gameobject are serialized and sent to the client? That would mean I need to implement a struct with the same properties as the live implementation.

Right. Replica components are serialized and sent to the client. Uchu has 2 ways to go about this, either by manually writing the serialization (see for example the [inventory component](https://github.com/UchuServer/Uchu/blob/caa7be2799eacba313f0c30835e50adb3d5ddf05/Uchu.World/Objects/Components/ReplicaComponents/InventoryComponent.cs#L252)), or using a struct (see for example the [bouncer component](https://github.com/UchuServer/Uchu/blob/caa7be2799eacba313f0c30835e50adb3d5ddf05/Uchu.World/Objects/Components/ReplicaComponents/BouncerComponent.cs#L29) and its [struct](https://github.com/UchuServer/Uchu/blob/caa7be2799eacba313f0c30835e50adb3d5ddf05/Uchu.World/Packets/Replica/Serialize/BouncerSerialization.cs), and the [vendor component](https://github.com/UchuServer/Uchu/blob/caa7be2799eacba313f0c30835e50adb3d5ddf05/Uchu.World/Objects/Components/ReplicaComponents/VendorComponent.cs#L44) and its [struct](https://github.com/UchuServer/Uchu/blob/caa7be2799eacba313f0c30835e50adb3d5ddf05/Uchu.World/Packets/Replica/Serialize/VendorSerialization.cs))

> That would then fix (some of) the problems?

Possibly - I don't know if this is indeed the component that should be implemented to fix this issue.
It's component no. 61 and is attached to objects 6416, 6577, 8092 and 9827. These are all modular assembly items (rocket, cars).

2021-09-12 15:15 UTC, TecCheck commented
I ran into yet another problem. Its about the `Item` class. At the moment it seems that items are handled a bit differently than other GameObjects. 

For example when an item is instantiated it doesn't automatically add its components based on the`ComponentRegistry` table although I think that can be fixed quite easily. There is a method called `InitializeComponents` in `GameObject`
 that handles all of that.

As well as that items don't register themselves in the zone (like player objects do) which means that none of the `Construct` methods of the replica components get called and no SerializeMessage is sent. That is needed for the `ModularAssemblyComponent` (and possibly others) to work properly.

At least that's what I think. I'm not really familiar with the code base.

I tried calling `Construct(instance)` in `Instantiate.Instantiate` to see if it would send a ConstructionPacket but it didn't.

2021-09-12 17:14 UTC, enteryournamehere commented
You're right - items currently don't have components initiated. I've looked at that briefly before, adding `instance.InitializeComponents();` on [this line](https://github.com/UchuServer/Uchu/blob/dev/Uchu.World/Objects/GameObjects/Item.cs#L87) should fix it iirc.

I'm not sure about the construction of items. Maybe someone else has something useful to add about that, otherwise I can look into it later this week.

2021-09-12 21:59 UTC, TecCheck commented
I've not see any Serialisation/Creation packet for a rocket in the captured packets. [The docs](https://docs.lu-dev.net/en/latest/replica.html) say that the `ModularAssemblyComponent` was sent but I'm really not sure...

2021-09-28 18:53 UTC, TecCheck commented
By the way the latest commit (dbe4fa1) may not be the best solution. Feedback is welcome.

2021-10-02 09:41 UTC, TecCheck commented
I'm now gonna leave out the remaining 2 Tasks because I just can't figure out what to implement to make them work. For this this reason it would be cool to get some feedback on the code from active devs if possible. I'm sure there are some things that could be improved.

2021-10-09 22:21 UTC, enteryournamehere requested changes
Looking good so far! I've left a couple comments but overall it looks great.
One thing I found when testing is that if I drop a whole rocket into the build area and then replace one of the parts with a different one from my inventory, I don't get the part that it's replacing back until I leave the build mode. Would it be possible to fix that? Replacing an individually placed part does work as expected.

2021-10-09 22:21 UTC, enteryournamehere commented on Uchu.World/Objects/Components/Player/ModularBuilderComponent.cs
> +        private static Lot GetModelLotForBuildMode(int mode)
I think it would be nice to store build modes as an enum instead of an int. You can also add the `Lot`s to `Lot.cs` as consts, so you can refer to them with, for example, `Lot.BuildBorderNimbusStation`.
Additionally I don't think a dict is the best thing to use here, a switch statement might make more sense, so you would end up with something like this:
```cs
switch(lot) {
    case Lot.NewRocketBay:
    case Lot.NimbusRocketBuildBorder:
    case Lot.LupRocketBuildBorder:
        return BuildMode.Rocket;
    case Lot.CarBuildBorder:
    case Lot.GnarledForestCarBuildBorder:
        return BuildMode.Car;
    default:
        return BuildMode.NotCustomized;
}
```
(Don't know what NotCustomized does & if that default value makes any sense - maybe Rocket or something else is better)

2021-10-09 22:21 UTC, enteryournamehere commented on Uchu.World/Handlers/GameMessages/ModularBuildingHandler.cs
> +            if (!player.TryGetComponent<CharacterComponent>(out var characterComponent))
The line below only runs if the player does _not_ have a Character component, I think this `!` shouldn't be here

2021-10-09 22:21 UTC, enteryournamehere commented on Uchu.World/Objects/Components/Player/InventoryManagerComponent.cs
> +                    var item = await Item.Instantiate(GameObject, lot, inventory, toAdd, extraInfo: settings, rootItem: rootItem, objectId: objectId);
I believe this could result in multiple stacks with the same ObjectId being created (when `count > stackSize` and `objectId` is specified), and that an `objectId = null;` line after this one should fix that

2021-10-10 15:00 UTC, teccheck commented
The thing that you found is intentional. I did it that way so you wouldn't lose your rocket. But if you think the UX is bad i can change that.

2021-10-10 15:03 UTC, teccheck commented on Uchu.World/Objects/Components/Player/ModularBuilderComponent.cs
> +        private static Lot GetModelLotForBuildMode(int mode)
The reason i did it that way is because LU did it that way. I found this [here](https://github.com/lcdr/lu-explorer/blob/1dca93fe5125aa8b2c127564e88b216a11a303ae/src/app/objects/components/item-component/item-component.component.html#L112). Still I can change it. 

Btw I too am not sure what "NotCustomized" is for. There are also some other modes

2021-10-10 15:04 UTC, teccheck commented on Uchu.World/Handlers/GameMessages/ModularBuildingHandler.cs
> +            if (!player.TryGetComponent<CharacterComponent>(out var characterComponent))
I'll change that. Maybe someone forgot a `return;` there.

2021-10-10 15:21 UTC, teccheck commented on Uchu.World/Objects/Components/Player/InventoryManagerComponent.cs
> +                    var item = await Item.Instantiate(GameObject, lot, inventory, toAdd, extraInfo: settings, rootItem: rootItem, objectId: objectId);
Done

2021-10-11 20:43 UTC, enteryournamehere commented on Uchu.World/Objects/Components/Player/ModularBuilderComponent.cs
> +        private static Lot GetModelLotForBuildMode(int mode)
Both methods achieve the same goal and have the same outputs for the same inputs. The only difference is that the one using a dict throws an exception when an invalid key is supplied, while `switch` + `default` prevents that. The `switch` method is also [about 24x as fast](https://dotnetfiddle.net/0EPq7n). (Not that that matters much, though; in that example it still runs 10k times in 1.5ms)

2021-10-11 21:09 UTC, enteryournamehere commented
Hmm, makes sense. Personally I do think it would be better to always give back the part you're replacing when working on a rocket. With the current implementation the part will be inaccessible until you quit building, so you can't drag a rocket into the build area, make two changes and then revert one of those; to use that part again you'd have to exit build mode, enter it again and load the rocket again.

2021-10-11 21:21 UTC, enteryournamehere commented on Uchu.World/Objects/Components/Player/ModularBuilderComponent.cs
> +            if (item == default || item == null)
This could be written as just `item == default`; the `default` for `Item` [is null because it is a reference type](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/default-values)

2021-10-12 06:00 UTC, TecCheck commented
Ok so then I'll change the behavior to just disassemble the rocket when the player puts it into the builder and if he quits he'll get the parts back

2021-10-13 14:16 UTC, teccheck commented on Uchu.World/Objects/Components/Player/ModularBuilderComponent.cs
> +        private static Lot GetModelLotForBuildMode(int mode)
There is already a `BuildMode` Enum. I'm not quite sure what purpose it has. Should I add the entries to it?

2021-10-24 20:58 UTC, enteryournamehere reviewed
Just one small comment but it's working perfectly :+1: love it

2021-10-24 20:58 UTC, enteryournamehere commented on Uchu.World/Objects/Components/Player/ModularBuilderComponent.cs
> +                    item = inventory.FindItem(lot, InventoryType.Models);
You can replace the if statement with just a `??`:

```suggestion
                var item = inventory.FindItem(lot, InventoryType.TemporaryModels) 
                           ?? inventory.FindItem(lot, InventoryType.Models);
```

2021-10-25 20:11 UTC, teccheck commented
OK, done :rocket:

2021-10-26 18:43 UTC, enteryournamehere approved these changes
:rocket: indeed - :car:, even

thank you for all these improvements!

2021-10-26 18:43 UTC, merged