Fix respawning for racing
yuwui/Uchu pull request #348
Opened 2023-08-21 13:49 UTC by enteryournamehere

The previous code
```c#
var playerInfo = Players.Find(info => info.Player.Id == player.Id);
playerInfo.Vehicle = car;
```
was broken because `Players` contains `RacingPlayerInfo` structs, which is a value type, not a reference type. This means that `var playerInfo = ...` results in a local copy of the data. The following line then only modifies this local copy, leaving `Players` unchanged.

This new code creates a local copy of the data, modifies it, and then updates the struct stored in the `Players` list.

2023-08-23 10:22 UTC, TecCheck requested changes
In line 233 there's another one of those bugs. To me it seems like it's working anyways but it might be good to fix this as well.

```cs
playerInfo = Players.Find(info => info.Player.Id == player.Id);
playerInfo.Player = player;
playerInfo.PlayerLoaded = true;
```
Other than that it looks good to me. 

I looked into [ref structs](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/ref-struct) but they don't seem to be the right choice

2023-08-23 10:29 UTC, enteryournamehere commented
Oh, good catch!

2023-08-23 10:47 UTC, TecCheck commented
I made this code after all... The more I look at it, the more I want to redo the whole thing xD

2023-08-28 14:00 UTC, teccheck approved these changes
Looks good to me. Thank you :+1:

2023-08-28 20:57 UTC, merged